### ISSUE TITLE
无法加载插件_(´ཀ`」 ∠)_

### ISSUE THREAD

**Issue by metheno** [metheno/typecho-theme-kibou#9]
就是我的Kibou加载不了插件…
应该是解析的问题

究极害怕，正在~~全力~~修复。

**Comment by Dalodd** [comment]
_(´ཀ`」 ∠)_

**Comment by metheno** [comment]
下次再修吧(⁎⁍̴̛ᴗ⁍̴̛⁎)

发自我的 iPad

**Comment by metheno** [comment]
我真是见了鬼了…？？？

![plugin_bug](https://cloud.githubusercontent.com/assets/16894767/23840989/e9a2b1d8-07e4-11e7-9fc6-d15f63cb41ef.png)

**Comment by ihewro** [comment]
footer.php 里面似乎没有加`<?php $this->footer(); ?>`
这个是插件输出代码的钩子

**Comment by metheno** [comment]
唔 这样啊 谢谢(˶‾᷄ ⁻̫ ‾᷅˵)

发自我的 iPad
